### ISSUE TITLE
Segmentation fault in nbt_free_list

### ISSUE THREAD

**Issue by opennota** [FliPPeh/cNBT#19]
The following program:

``` C
#include <stdio.h>
#include <string.h>
#include <nbt.h>

int main(int argc, const char *argv[]) {
	FILE *in = stdin;
	if (argc > 1) {
		in = fopen(argv[1], "rb");
		if (!in) {
			perror("fopen");
			return -1;
		}
	}

	char buf[65536];
	size_t len = fread(buf, 1, sizeof(buf), in);
	nbt_parse(buf, len);
}
```

segfaults on this input:

```
$ echo -ne '\x09\x00\x00' | ./prog
Segmentation fault (core dumped)
```

```
(gdb) r

Program received signal SIGSEGV, Segmentation fault.
0x0000000000402d87 in nbt_free_list (list=0x6072a0) at nbt_treeops.c:42
42          list_for_each_safe(current, temp, &list->entry)

(gdb) bt
#0  0x0000000000402d87 in nbt_free_list (list=0x6072a0) at nbt_treeops.c:42
#1  0x0000000000401588 in read_list (memory=0x7ffffffed8c8, length=0x7ffffffed8c0) at nbt_parsing.c:279
#2  0x0000000000401a05 in parse_unnamed_tag (type=TAG_LIST, name=0x607250 "", memory=0x7ffffffed8c8, 
    length=0x7ffffffed8c0) at nbt_parsing.c:379
#3  0x0000000000401b1f in nbt_parse (mem=0x7ffffffed933, len=0) at nbt_parsing.c:422
```

#afl

**Comment by cgaebel** [comment]
Thanks a ton for this bug report. #afl indeed.

**Comment by cgaebel** [comment]
Please confirm this fix works for you!
